spring:
  application:
    name: OAUTH
  zipkin:
    baseUrl: http://msa-trace.development.svc.cluster.local:9411
  sleuth:
    sampler:
      percentage: 0.2
  http:
    encoding:
      force: true
      charset: UTF-8
server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://apireg-0.msa-apireg.development.svc.cluster.local:8761/eureka/,http://apireg-1.msa-apireg.development.svc.cluster.local:8761/eureka/
  instance:
    preferIpAddress: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
logging:
  config: classpath:logback-dev.xml