server:
  port: 9411
spring:
  application:
    name: TRACE
  datasource:
    initialize: false
  sleuth:
    enabled: false
zipkin:
  store:
    type: mem
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://apireg-0.msa-apireg.development.svc.cluster.local:8761/eureka/,http://apireg-1.msa-apireg.development.svc.cluster.local:8761/eureka/
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
logging:
  config: classpath:logback-dev.xml